# Generated by Django 5.2.4 on 2025-07-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eletronicos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariosmodel",
            name="categorias",
            field=models.CharField(
                choices=[
                    ("celular", "Celular"),
                    ("notebook", "Notebook"),
                    ("fones", "Fones"),
                    ("computadores", "Computadores"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
