# Generated by Django 5.2.4 on 2025-07-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eletronicos", "0002_usuariosmodel_categorias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariosmodel",
            name="data_criacao",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
