# Generated by Django 5.2.4 on 2025-07-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eletronicos", "0003_alter_usuariosmodel_data_criacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariosmodel",
            name="status",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
