# Generated by Django 5.2.4 on 2025-07-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eletronicos", "0004_usuariosmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariosmodel",
            name="status",
            field=models.BooleanField(
                choices=[
                    ("concluida", "Concluida"),
                    ("pendente", "Pendente"),
                    ("Em analise", "Em andamento"),
                ],
                default=True,
            ),
        ),
    ]
