# Generated by Django 5.2.4 on 2025-07-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eletronicos", "0005_alter_usuariosmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariosmodel",
            name="status",
            field=models.BooleanField(
                choices=[(True, "Concluida"), (False, "Pendente")], default=True
            ),
        ),
    ]
