# Generated by Django 5.2.4 on 2025-07-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eletronicos", "0006_alter_usuariosmodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariosmodel",
            name="arquivo",
            field=models.FileField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
