# Generated by Django 5.2.4 on 2025-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eletronicos", "0007_usuariosmodel_arquivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariosmodel",
            name="imagem",
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name="usuariosmodel",
            name="arquivo",
            field=models.FileField(blank=True, default=None, upload_to=None),
        ),
    ]
