# Generated by Django 5.2.4 on 2025-07-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eletronicos', '0010_alter_usuariosmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosmodel',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='usuariosmodel',
            name='imagem',
        ),
    ]
