# Generated by Django 5.2.4 on 2025-07-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eletronicos', '0011_remove_usuariosmodel_arquivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariosmodel',
            old_name='nome',
            new_name='produto',
        ),
    ]
