# Generated by Django 5.2.2 on 2025-07-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletronicos', '0012_rename_nome_usuariosmodel_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosmodel',
            name='categorias',
            field=models.CharField(choices=[('Celular', 'Celular'), ('Notebook', 'Notebook'), ('Fones', 'Fones'), ('Computadores', 'Computadores')]),
        ),
        migrations.AlterField(
            model_name='usuariosmodel',
            name='produto',
            field=models.CharField(),
        ),
    ]
