# Generated by Django 5.2.2 on 2025-07-29 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eletronicos', '0013_alter_usuariosmodel_categorias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosmodel',
            name='email',
        ),
    ]
