# Generated by Django 5.2.2 on 2025-07-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletronicos', '0014_remove_usuariosmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosmodel',
            name='usuarios',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
