# Generated by Django 5.2.6 on 2025-10-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletronicos', '0015_usuariosmodel_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosmodel',
            name='produto',
            field=models.CharField(max_length=50),
        ),
    ]
