# Generated by Django 6.0.3 on 2026-03-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletronicos', '0016_alter_usuariosmodel_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosmodel',
            name='setor',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
