# Generated by Django 6.0.3 on 2026-03-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletronicos', '0017_usuariosmodel_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosmodel',
            name='setor',
            field=models.CharField(choices=[('Faturamento', 'Faturamento'), ('Recursos Humanos', 'Recursos Humanos'), ('Comercial', 'Comercial'), ('TI', 'TI')]),
        ),
    ]
